import { defineConfig } from 'vitepress';
import { createRequire } from 'node:module';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const pkg = require('../../package.json');

/**
 * The API reference under `docs/reference/` is generated by TypeDoc, which also
 * emits its own sidebar. Load it when it exists so `vitepress dev` still starts
 * on a fresh clone where `npm run docs:api` has not run yet.
 */
const referenceSidebarPath = fileURLToPath(
  new URL('../reference/typedoc-sidebar.json', import.meta.url),
);
const referenceSidebar = existsSync(referenceSidebarPath)
  ? require(referenceSidebarPath)
  : [{ text: 'Run `npm run docs:api` to generate', link: '/guide/' }];

export default defineConfig({
  title: 'shapefile-wasm',
  description:
    'Read and write ESRI Shapefiles from GeoJSON in the browser, Node and workers. Rust core compiled to WebAssembly.',

  // Relative links so the built site works from a subdirectory, which is what
  // GitHub Pages serves for a project repo.
  base: process.env.DOCS_BASE ?? '/',
  cleanUrls: true,
  lastUpdated: true,

  head: [
    ['meta', { name: 'theme-color', content: '#3c7f4f' }],
    ['meta', { property: 'og:title', content: 'shapefile-wasm' }],
    [
      'meta',
      {
        property: 'og:description',
        content: 'ESRI Shapefiles in the browser, via Rust and WebAssembly.',
      },
    ],
  ],

  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/', activeMatch: '/guide/' },
      { text: 'Demo', link: '/demo', activeMatch: '/demo' },
      {
        text: 'API',
        activeMatch: '/reference/',
        items: [
          { text: 'TypeScript reference', link: '/reference/' },
          { text: 'Rust reference', link: '/rust' },
        ],
      },
      {
        text: `v${pkg.version}`,
        items: [
          { text: 'Changelog', link: '/guide/changelog' },
          { text: 'npm', link: 'https://www.npmjs.com/package/@crmackey/shapefile-wasm' },
        ],
      },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'What it is', link: '/guide/' },
            { text: 'Getting started', link: '/guide/getting-started' },
            { text: 'Entry points', link: '/guide/entry-points' },
          ],
        },
        {
          text: 'Using it',
          items: [
            { text: 'Writing shapefiles', link: '/guide/writing' },
            { text: 'Reading shapefiles', link: '/guide/reading' },
            { text: 'Multiple layers', link: '/guide/multiple-layers' },
            { text: 'Projections', link: '/guide/projections' },
            { text: 'In the browser', link: '/guide/browser' },
          ],
        },
        {
          text: 'Reference',
          items: [
            { text: 'Format mapping', link: '/guide/format-mapping' },
            { text: 'Known limits', link: '/guide/limits' },
            { text: 'Troubleshooting', link: '/guide/troubleshooting' },
          ],
        },
        {
          text: 'Contributing',
          items: [
            { text: 'Development', link: '/guide/development' },
            { text: 'Testing', link: '/guide/testing' },
            { text: 'Architecture', link: '/guide/architecture' },
            { text: 'Changelog', link: '/guide/changelog' },
          ],
        },
      ],
      '/reference/': referenceSidebar,
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/CalebM1987/shapefile-wasm' }],

    search: { provider: 'local' },

    editLink: {
      pattern: 'https://github.com/CalebM1987/shapefile-wasm/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: 'Released under the MIT License.',
      copyright: `Copyright © ${new Date().getFullYear()} Caleb Mackey`,
    },

    outline: { level: [2, 3] },
  },

  // The generated reference contains links TypeDoc resolves at build time; do
  // not fail the whole build over one of them.
  // Both are separate static sites staged into dist/, outside the router.
  ignoreDeadLinks: [/^\/reference\//, /^\/app\//, /^\/rustdoc\//],
});
