/**
 * Publishes the llms.txt files into the documentation site.
 *
 * `llms.txt` is authored by hand at the repository root — it is a curated
 * summary, not something worth generating — and shipped in the npm tarball so
 * tooling can find it inside node_modules. This copies it to the site root and
 * builds the `llms-full.txt` companion by concatenating the guide.
 *
 * Both land in `docs/public/`, which VitePress copies to the site root
 * verbatim, so they end up at /llms.txt and /llms-full.txt.
 */
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const GUIDE = resolve(ROOT, 'docs/guide');
const PUBLIC = resolve(ROOT, 'docs/public');

/** Reading order, so the concatenation tells a story rather than being alphabetical. */
const ORDER = [
  'index',
  'getting-started',
  'entry-points',
  'writing',
  'reading',
  'multiple-layers',
  'projections',
  'browser',
  'format-mapping',
  'limits',
  'troubleshooting',
  'architecture',
  'development',
  'testing',
];

const index = await readFile(resolve(ROOT, 'llms.txt'), 'utf8');

const available = new Set(
  (await readdir(GUIDE)).filter((f) => f.endsWith('.md')).map((f) => f.replace(/\.md$/, '')),
);

// A page added to the guide but not listed here would be silently missing from
// llms-full.txt, which is exactly the kind of drift nobody notices.
const unlisted = [...available].filter((n) => !ORDER.includes(n) && n !== 'changelog');
if (unlisted.length > 0) {
  console.error(
    `guide pages missing from the llms-full.txt order: ${unlisted.join(', ')}\n` +
      'Add them to ORDER in scripts/build-llms.mjs.',
  );
  process.exit(1);
}

const sections = [];
for (const name of ORDER) {
  if (!available.has(name)) {
    console.error(`llms.txt order lists "${name}", which is not in docs/guide/`);
    process.exit(1);
  }

  let body = await readFile(resolve(GUIDE, `${name}.md`), 'utf8');

  // Strip frontmatter and VitePress-only syntax so the result reads as plain
  // markdown to something that has never heard of VitePress.
  body = body.replace(/^---\n[\s\S]*?\n---\n/, '');
  body = body.replace(/^<script setup>[\s\S]*?<\/script>\n/m, '');
  body = body.replace(/^<style>[\s\S]*?<\/style>\n/m, '');
  body = body.replace(/^::: \w+(?: .*)?$/gm, '').replace(/^:::$/gm, '');

  sections.push(body.trim());
}

const full = `${index.trim()}

---

# Full documentation

The complete guide, concatenated. Generated by scripts/build-llms.mjs.

---

${sections.join('\n\n---\n\n')}
`;

await mkdir(PUBLIC, { recursive: true });
await writeFile(resolve(PUBLIC, 'llms.txt'), index, 'utf8');
await writeFile(resolve(PUBLIC, 'llms-full.txt'), full, 'utf8');

const kb = (s) => `${(Buffer.byteLength(s) / 1024).toFixed(1)} KiB`;
console.log(`wrote llms.txt (${kb(index)}) and llms-full.txt (${kb(full)}) into docs/public`);
