/**
 * Prepares the wasm-pack output for the TypeScript build.
 *
 * Two jobs:
 *
 * 1. Embed the compiled `.wasm` into a module as base64. This is what lets the
 *    package root work with no bundler configuration — there is no separate
 *    asset to resolve, copy or serve. `/slim` consumers stream the real binary
 *    instead.
 * 2. Copy the wasm-bindgen glue into `src/generated/`. `tsc` refuses to emit for
 *    sources outside `rootDir`, so the glue has to live under `src/` rather than
 *    being imported from `../pkg`.
 */
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, '../pkg');
const GENERATED = resolve(HERE, '../src/generated');

await mkdir(GENERATED, { recursive: true });

// 1. Inline the binary.
const binary = await readFile(resolve(PKG, 'shapefile_wasm_bg.wasm'));
const base64 = binary.toString('base64');

const source = `// Generated by scripts/inline-wasm.mjs — do not edit by hand.
// The WebAssembly binary, base64-encoded so the package needs no separate asset.

const ENCODED =
  '${base64}';

let cached: Uint8Array | undefined;

/**
 * Decodes the embedded binary. The result is cached, so re-initialising or
 * running several times in the same realm only pays the decode once.
 */
export function wasmBytes(): Uint8Array {
  if (cached) return cached;

  // Buffer is the faster path where it exists; \`atob\` covers browsers.
  if (typeof Buffer !== 'undefined') {
    cached = new Uint8Array(Buffer.from(ENCODED, 'base64'));
    return cached;
  }

  const binary = atob(ENCODED);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) {
    bytes[i] = binary.charCodeAt(i);
  }
  cached = bytes;
  return cached;
}

/** Size of the embedded binary in bytes, before base64 encoding. */
export const wasmByteLength = ${binary.byteLength};
`;

await writeFile(resolve(GENERATED, 'wasm-inline.ts'), source, 'utf8');

// 2. Bring the glue under src/.
await copyFile(resolve(PKG, 'shapefile_wasm.js'), resolve(GENERATED, 'bindings.js'));
await copyFile(resolve(PKG, 'shapefile_wasm.d.ts'), resolve(GENERATED, 'bindings.d.ts'));

const kb = (n) => `${(n / 1024).toFixed(1)} KiB`;
console.log(
  `inlined ${kb(binary.byteLength)} of wasm as ${kb(base64.length)} of base64; copied bindings`,
);
